apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  creationTimestamp: null
  name: team-graph-microsoft
  namespace: team-onboarding
spec:
  exportTo:
  - .
  hosts:
  - graph.microsoft.com
  ports:
  - name: https
    number: 443
    protocol: HTTPS
  resolution: DNS
status: {}
