# Copyright (c) 2023 Volvo Car Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nope
    app.kubernetes.io/part-of: nope
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
